/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package id.co.indocyber.nasabah;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.List;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ListSelectionModel;
import javax.swing.RowFilter;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author user
 */
public class TableRowSelection extends javax.swing.JFrame {

    private int jmlTanggungan;
    private double gajiPokok;
    private double penghasilanTambahan;
    private double hargaBarang;
    private double uangMuka;
    private int lamaKredit;
    
    /**
     * Creates new form TableRowSelection
     */
    public TableRowSelection() throws IOException {
        initComponents();
        showPeople();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void showPeople() throws IOException {
        DefaultTableModel model = (DefaultTableModel) tabelPerson.getModel();
        Person pers = new Person();
        List<Person> data = getPeople("C:/Users/user/Documents/NetBeansProjects/AplikasiManajemenNasabah/datanasabah.txt");
        //List<Person> data = getPeople("D:/Users/Maryam/Documents/NetBeansProjects/AplikasiManajemenNasabah/datanasabah.txt");
        Object[] row = new Object[4];
        for (Person person : data) {
            row[0] = person.getName();
            row[1] = person.getGender();
            row[2] = person.getMaried();
            row[3] = person.getAge();

            model.addRow(row);
        }

        ListSelectionModel rowSelMod = tabelPerson.getSelectionModel();
        rowSelMod.addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if (!e.getValueIsAdjusting()) {
                    // System.out.println("row diklik");
                    int i = tabelPerson.getSelectedRow();
                    String nama = (String) model.getValueAt(i, 0);
                    String gender = (String) model.getValueAt(i, 1);
                    boolean maried = (boolean) model.getValueAt(i, 2);
                    //String age = model.getValueAt(i, 3).toString();
                    String age = (String)model.getValueAt(i, 3);
                    System.out.println("row ");
                    txtNama.setText(nama);
                    cmbGender.setSelectedItem(gender);
                    chkStatusPernikahan.setSelected(maried);
                    txtUmur.setText(age);
                    txtIdentitas.setText(data.get(i).getNoIdentitas());
                    txtPekerjaan.setText(data.get(i).getPekerjaan());
                    txtAlamat.setText(data.get(i).getAlamat());
                    txtTelepon.setText(data.get(i).getNoTelepon());
                    txtTanggungan.setText(String.valueOf(data.get(i).getJmlTanggungan()));
                    txtGajiPokok.setText(String.valueOf(data.get(i).getGajiPokok()));
                    txtPenghasilanTambahan.setText(String.valueOf(data.get(i).getPenghasilanTambahan()));
                    txtNamaBarang.setText(data.get(i).getNamaBarang());
                    txtHargaBarang.setText(String.valueOf(data.get(i).getHargaBarang()));
                    txtUangMuka.setText(String.valueOf(data.get(i).getUangMuka()));
                    txtLamaKredit.setText(String.valueOf(data.get(i).getLamaKredit()));
                }
            }
        });

    }

    
    private List<Person> getPeople(String filename) throws FileNotFoundException, IOException {
        List<Person> people = new ArrayList<>();
        File file = new File(filename);
        FileReader fileReader = new FileReader(file);
        BufferedReader reader = new BufferedReader(fileReader);

        List<Person> person = new ArrayList<>();
        String line = null;

        while ((line = reader.readLine()) != null) {
            String splitLine[] = line.split(",");

            //Person peop = new Person(splitLine[0].trim(), splitLine[1].trim(), Boolean.parseBoolean(splitLine[2].trim()), splitLine[3].trim());
            //Person peop = new Person(splitLine[0].trim(), splitLine[1].trim(), Boolean.parseBoolean(splitLine[2].trim()), splitLine[3].trim(), splitLine[4].trim(), splitLine[5].trim(), splitLine[6].trim(), splitLine[7].trim(), Integer.parseInt(splitLine[8].trim()), Integer.parseInt(splitLine[9].trim()), Integer.parseInt(splitLine[10].trim()));
            Person peop = new Person(splitLine[0].trim(), splitLine[1].trim(), Boolean.parseBoolean(splitLine[2].trim()), splitLine[3].trim(), splitLine[4].trim(), splitLine[5].trim(), splitLine[6].trim(), splitLine[7].trim(), Integer.parseInt(splitLine[8].trim()), Integer.parseInt(splitLine[9].trim()), Integer.parseInt(splitLine[10].trim()), splitLine[11].trim(), Integer.parseInt(splitLine[12].trim()), Integer.parseInt(splitLine[13].trim()), Integer.parseInt(splitLine[14].trim()));
            person.add(peop);
        }
        return person;
    }

//    private List<Person> getDataPerson(String filename) throws FileNotFoundException, IOException {
//        File file = new File("tModel.addRow(row);");
//        FileReader fileReader = new FileReader(file);
//        BufferedReader reader = new BufferedReader(fileReader);
//
//        List<Person> dataPerson = new ArrayList<>();
//        String line = null;
//
//        while ((line = reader.readLine()) != null) {
//            String splitLine[] = line.split(",");
//
//            Person peop = new Person(splitLine[0].trim(), splitLine[1].trim(), Boolean.parseBoolean(splitLine[2].trim()), splitLine[3].trim());
//            dataPerson.add(peop);
//        }
//        return dataPerson;
//    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlJudul = new javax.swing.JPanel();
        txtJudul = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pnlUtama = new javax.swing.JPanel();
        panelTabel = new javax.swing.JPanel();
        txtFilter = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelPerson = new javax.swing.JTable();
        jLabel21 = new javax.swing.JLabel();
        pnlInputDetail = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        cmbGender = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtUmur = new javax.swing.JTextField();
        chkStatusPernikahan = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        txtIdentitas = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtPekerjaan = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtAlamat = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtTelepon = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtTanggungan = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtGajiPokok = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtPenghasilanTambahan = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtTotalPenghasilan = new javax.swing.JTextField();
        cmbHitung = new javax.swing.JButton();
        pnlDetaiKredit = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        txtNamaBarang = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtHargaBarang = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtUangMuka = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtLamaKredit = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txtPokokCicilan = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtSukuBungaPerTahun = new javax.swing.JTextField();
        txtTotalKredit = new javax.swing.JTextField();
        txtLimitPinjaman = new javax.swing.JTextField();
        txtCicilanPerBulan = new javax.swing.JTextField();
        txtBungaCicilan = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        txtStatusCicilan = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlJudul.setBackground(new java.awt.Color(0, 204, 204));
        pnlJudul.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        txtJudul.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        txtJudul.setText("Aplikasi Manajemen Nasabah");

        javax.swing.GroupLayout pnlJudulLayout = new javax.swing.GroupLayout(pnlJudul);
        pnlJudul.setLayout(pnlJudulLayout);
        pnlJudulLayout.setHorizontalGroup(
            pnlJudulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlJudulLayout.createSequentialGroup()
                .addGap(187, 187, 187)
                .addComponent(txtJudul)
                .addContainerGap(223, Short.MAX_VALUE))
        );
        pnlJudulLayout.setVerticalGroup(
            pnlJudulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlJudulLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtJudul)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pnlUtama.setBackground(new java.awt.Color(0, 204, 204));

        panelTabel.setBackground(new java.awt.Color(0, 204, 204));
        panelTabel.setBorder(javax.swing.BorderFactory.createTitledBorder("Data Nasabah"));

        txtFilter.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtFilterCaretUpdate(evt);
            }
        });

        tabelPerson.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nama", "Jenis Kelamin", "Status Pernikahan", "Umur"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Boolean.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tabelPerson);

        jLabel21.setText("Filter :");

        javax.swing.GroupLayout panelTabelLayout = new javax.swing.GroupLayout(panelTabel);
        panelTabel.setLayout(panelTabelLayout);
        panelTabelLayout.setHorizontalGroup(
            panelTabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTabelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTabelLayout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addGap(42, 42, 42)
                        .addComponent(txtFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 669, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelTabelLayout.setVerticalGroup(
            panelTabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTabelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pnlInputDetail.setBackground(new java.awt.Color(0, 204, 204));
        pnlInputDetail.setBorder(javax.swing.BorderFactory.createTitledBorder("Input Detail"));

        jLabel1.setText("Nama : ");

        jLabel2.setText("Jenis Kelamin :");

        cmbGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laki-laki", "Perempuan" }));

        jLabel4.setText("Umur : ");

        chkStatusPernikahan.setText("Menikah");

        jLabel3.setText("No. Identitas :");

        jLabel5.setText("Status Pernikahan :");

        jLabel6.setText("Pekerjaan :");

        jLabel7.setText("Alamat :");

        jLabel8.setText("No. Telepon :");

        jLabel9.setText("Jml. Tanggungan :");

        jLabel10.setText("Gaji Pokok :");

        jLabel11.setText("Penghasilan Tambahan :");

        jLabel12.setText("Total Penghasilan :");

        cmbHitung.setText("Hitung");
        cmbHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbHitungActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlInputDetailLayout = new javax.swing.GroupLayout(pnlInputDetail);
        pnlInputDetail.setLayout(pnlInputDetailLayout);
        pnlInputDetailLayout.setHorizontalGroup(
            pnlInputDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInputDetailLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlInputDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6)
                    .addComponent(jLabel3)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlInputDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlInputDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(chkStatusPernikahan)
                        .addComponent(txtIdentitas)
                        .addComponent(txtNama)
                        .addComponent(txtUmur)
                        .addComponent(cmbGender, 0, 193, Short.MAX_VALUE)
                        .addComponent(txtAlamat))
                    .addComponent(txtPekerjaan, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(pnlInputDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlInputDetailLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtTotalPenghasilan, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlInputDetailLayout.createSequentialGroup()
                        .addGroup(pnlInputDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlInputDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlInputDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtTelepon, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtTanggungan, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtGajiPokok, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlInputDetailLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtPenghasilanTambahan, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cmbHitung, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlInputDetailLayout.setVerticalGroup(
            pnlInputDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInputDetailLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlInputDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(txtTelepon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlInputDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txtTanggungan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(pnlInputDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkStatusPernikahan)
                    .addComponent(jLabel5)
                    .addComponent(jLabel10)
                    .addComponent(txtGajiPokok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlInputDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtUmur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(txtPenghasilanTambahan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlInputDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtIdentitas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(txtTotalPenghasilan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlInputDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlInputDetailLayout.createSequentialGroup()
                        .addGroup(pnlInputDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlInputDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(txtPekerjaan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(cmbHitung, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlDetaiKredit.setBackground(new java.awt.Color(0, 204, 204));
        pnlDetaiKredit.setBorder(javax.swing.BorderFactory.createTitledBorder("Detail Kredit"));

        jLabel13.setText("Nama Barang :");

        txtNamaBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaBarangActionPerformed(evt);
            }
        });

        jLabel14.setText("Harga Barang :");

        jLabel15.setText("Uang Muka :");

        jLabel16.setText("Lama Kredit :");

        txtLamaKredit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLamaKreditActionPerformed(evt);
            }
        });

        jLabel17.setText("Pokok Cicilan :");

        jLabel19.setText("Bunga Cicilan :");

        jLabel20.setText("Total Kredit :");

        jLabel22.setText("Limit Pinjaman");

        jLabel23.setText("Cicilan Per Bulan :");

        jLabel18.setText("Suku Bunga Per Tahun :");

        txtSukuBungaPerTahun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSukuBungaPerTahunActionPerformed(evt);
            }
        });

        txtCicilanPerBulan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCicilanPerBulanActionPerformed(evt);
            }
        });

        jLabel24.setText("Status Cicilan :");

        javax.swing.GroupLayout pnlDetaiKreditLayout = new javax.swing.GroupLayout(pnlDetaiKredit);
        pnlDetaiKredit.setLayout(pnlDetaiKreditLayout);
        pnlDetaiKreditLayout.setHorizontalGroup(
            pnlDetaiKreditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDetaiKreditLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDetaiKreditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(pnlDetaiKreditLayout.createSequentialGroup()
                        .addGroup(pnlDetaiKreditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18)
                            .addComponent(jLabel20)
                            .addComponent(jLabel22)
                            .addComponent(jLabel23)
                            .addComponent(jLabel24)
                            .addComponent(jLabel19))
                        .addGap(23, 23, 23)
                        .addGroup(pnlDetaiKreditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPokokCicilan)
                            .addComponent(txtSukuBungaPerTahun)
                            .addComponent(txtTotalKredit)
                            .addComponent(txtLimitPinjaman)
                            .addComponent(txtCicilanPerBulan)
                            .addComponent(txtBungaCicilan)
                            .addComponent(txtStatusCicilan)))
                    .addGroup(pnlDetaiKreditLayout.createSequentialGroup()
                        .addGroup(pnlDetaiKreditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16))
                        .addGap(66, 66, 66)
                        .addGroup(pnlDetaiKreditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtHargaBarang)
                            .addComponent(txtUangMuka)
                            .addComponent(txtLamaKredit, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                            .addComponent(txtNamaBarang))))
                .addContainerGap())
        );
        pnlDetaiKreditLayout.setVerticalGroup(
            pnlDetaiKreditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDetaiKreditLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDetaiKreditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtNamaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlDetaiKreditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(txtHargaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlDetaiKreditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(txtUangMuka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlDetaiKreditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(txtLamaKredit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlDetaiKreditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txtPokokCicilan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(pnlDetaiKreditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txtSukuBungaPerTahun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlDetaiKreditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(txtBungaCicilan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlDetaiKreditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(txtTotalKredit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlDetaiKreditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(txtLimitPinjaman, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlDetaiKreditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(txtCicilanPerBulan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlDetaiKreditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel24)
                    .addComponent(txtStatusCicilan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlUtamaLayout = new javax.swing.GroupLayout(pnlUtama);
        pnlUtama.setLayout(pnlUtamaLayout);
        pnlUtamaLayout.setHorizontalGroup(
            pnlUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUtamaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelTabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlInputDetail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(pnlDetaiKredit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        pnlUtamaLayout.setVerticalGroup(
            pnlUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUtamaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlDetaiKredit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlUtamaLayout.createSequentialGroup()
                        .addComponent(panelTabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlInputDetail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jScrollPane1.setViewportView(pnlUtama);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlJudul, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1124, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlJudul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(545, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 122, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNamaBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaBarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaBarangActionPerformed

    private void txtLamaKreditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLamaKreditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLamaKreditActionPerformed

    private void txtSukuBungaPerTahunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSukuBungaPerTahunActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSukuBungaPerTahunActionPerformed

    private void txtCicilanPerBulanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCicilanPerBulanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCicilanPerBulanActionPerformed

    private void cmbHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbHitungActionPerformed
        
        txtTotalPenghasilan.setText("6000000");
        txtPokokCicilan.setText("20000000");
        txtSukuBungaPerTahun.setText("5");
        txtBungaCicilan.setText("1000000");
        txtTotalKredit.setText("21000000");
        txtLimitPinjaman.setText("2000000");
        txtCicilanPerBulan.setText("1500000");
        txtStatusCicilan.setText("Disetujui");
        
    }//GEN-LAST:event_cmbHitungActionPerformed

    private void txtFilterCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtFilterCaretUpdate
        // TODO add your handling code here:
        TableRowSorter<TableModel> sorter = new TableRowSorter<>(((DefaultTableModel) tabelPerson.getModel()));
        sorter.setRowFilter(RowFilter.regexFilter(txtFilter.getText()));
        tabelPerson.setRowSorter(sorter);
    }//GEN-LAST:event_txtFilterCaretUpdate


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TableRowSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TableRowSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TableRowSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TableRowSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new TableRowSelection().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(TableRowSelection.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox chkStatusPernikahan;
    private javax.swing.JComboBox<String> cmbGender;
    private javax.swing.JButton cmbHitung;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel panelTabel;
    private javax.swing.JPanel pnlDetaiKredit;
    private javax.swing.JPanel pnlInputDetail;
    private javax.swing.JPanel pnlJudul;
    private javax.swing.JPanel pnlUtama;
    private javax.swing.JTable tabelPerson;
    private javax.swing.JTextField txtAlamat;
    private javax.swing.JTextField txtBungaCicilan;
    private javax.swing.JTextField txtCicilanPerBulan;
    private javax.swing.JTextField txtFilter;
    private javax.swing.JTextField txtGajiPokok;
    private javax.swing.JTextField txtHargaBarang;
    private javax.swing.JTextField txtIdentitas;
    private javax.swing.JLabel txtJudul;
    private javax.swing.JTextField txtLamaKredit;
    private javax.swing.JTextField txtLimitPinjaman;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNamaBarang;
    private javax.swing.JTextField txtPekerjaan;
    private javax.swing.JTextField txtPenghasilanTambahan;
    private javax.swing.JTextField txtPokokCicilan;
    private javax.swing.JTextField txtStatusCicilan;
    private javax.swing.JTextField txtSukuBungaPerTahun;
    private javax.swing.JTextField txtTanggungan;
    private javax.swing.JTextField txtTelepon;
    private javax.swing.JTextField txtTotalKredit;
    private javax.swing.JTextField txtTotalPenghasilan;
    private javax.swing.JTextField txtUangMuka;
    private javax.swing.JTextField txtUmur;
    // End of variables declaration//GEN-END:variables
}
